// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
	public class SharedController
	{

		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
            static readonly _LayoutsClass s_Layouts = new _LayoutsClass();
            public _LayoutsClass Layouts { get { return s_Layouts; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _LayoutsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Layout_01 = "_Layout_01";
                    public readonly string _Layout_02 = "_Layout_02";
                    public readonly string _Layout_03 = "_Layout_03";
                    public readonly string _Layout_04 = "_Layout_04";
                    public readonly string _Layout_05 = "_Layout_05";
                    public readonly string _Layout_06 = "_Layout_06";
                    public readonly string _Layout_07 = "_Layout_07";
                    public readonly string _Layout_08 = "_Layout_08";
                    public readonly string _Layout_09 = "_Layout_09";
                }
                public readonly string _Layout_01 = "~/Views/Shared/Layouts/_Layout_01.cshtml";
                public readonly string _Layout_02 = "~/Views/Shared/Layouts/_Layout_02.cshtml";
                public readonly string _Layout_03 = "~/Views/Shared/Layouts/_Layout_03.cshtml";
                public readonly string _Layout_04 = "~/Views/Shared/Layouts/_Layout_04.cshtml";
                public readonly string _Layout_05 = "~/Views/Shared/Layouts/_Layout_05.cshtml";
                public readonly string _Layout_06 = "~/Views/Shared/Layouts/_Layout_06.cshtml";
                public readonly string _Layout_07 = "~/Views/Shared/Layouts/_Layout_07.cshtml";
                public readonly string _Layout_08 = "~/Views/Shared/Layouts/_Layout_08.cshtml";
                public readonly string _Layout_09 = "~/Views/Shared/Layouts/_Layout_09.cshtml";
            }
		}
	}

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
